### ISSUE TITLE
Change language of FB button on profile view

### ISSUE THREAD

**Issue by dragonjon** [ColdTrick/profile_manager#103]
Hi guys, in the file \profile_manager\views\default\output\pm_facebook.php in the line 32 use FB JScript
js.src = "//connect.facebook.net/nl_NL/sdk.js#xfbml=1&version=v2.3" this scripts is for Netherlands language
I change for Spain modifying nl_NL with es_ES.
I propose can change the language of the escript automatically with the site language selected

Thanks for your work
Jon

**Comment by jdalsem** [comment]
the facebook button has been removed as facebook no longer has a "follow me on facebook" button
