### ISSUE TITLE
Add placeholder on backup action

### ISSUE THREAD

**Issue by abukaab** [ColdTrick/profile_manager#110]
There is no placeholder in backup action. 
So, I can't backup-restore my field's placeholder.

I tried it by adding 
`
		'metadata_placeholder' => $entity->metadata_placeholder,
`
in profile_manager/actions/configuration/backup.php line 38, it works properly.

**Comment by jdalsem** [comment]
Thanks for reporting. The fix has been added. The next version (for Elgg 3) will have this fix included
