### ISSUE TITLE
Problem installation

### ISSUE THREAD

**Issue by Elggfoundout** [ColdTrick/profile_manager#118]
Hello,

After installation 'Profile Manager' I read: 'This plugin is invalid: Cannot find a parser for manifest API version 1.7 in plugin custom_profile_fields.	Location: /home/watchmen/public_html/mod/custom_profile_fields/'

Cannot activate. Is their an solution?

Ariel

**Comment by jdalsem** [comment]
You probably downloaded the wrong version or installed it in the wrong directory
