### ISSUE TITLE
Failed to load "jquery/multiselect.js" when "Use symbolic link to simple cache directory" setting is enabled

### ISSUE THREAD

**Issue by oseg** [ColdTrick/profile_manager#119]
Context: elgg v2.3.7 & profile_manager v13.0.1

This is a regression, this issue did not happen in profile_manager v12

**Comment by jdalsem** [comment]
in v13 a different install path for the jquery/multiselect has been implemented, however you should have no issue when upgrading. I have no issues myself with this new location. Maybe a cache flush is required?
