### ISSUE TITLE
No custom fields when no standard profile fields are configured

### ISSUE THREAD

**Issue by dploeger** [ColdTrick/profile_manager#123]
If you have no profile types and no fields configured in the "standard" category, but in different other categories, the custom profile fields aren't displayed at all.

This is caused [by this line](https://github.com/ColdTrick/profile_manager/blob/master/views/default/profile_manager/admin/useradd.php#L18) where either profile types or fields in the standard category are required.

I'd suggest checking for `empty($types) && empty($fields)`, because I see no reason for this.

**Comment by jdalsem** [comment]
Thanks for reporting!
