### ISSUE TITLE
Fields added to the registration form are not saved in the user profile

### ISSUE THREAD

**Issue by RiverVanRain** [ColdTrick/profile_manager#127]
**Elgg version**
3.3.20

**Plugin version**
15.0.2

**Plugin source**
- Github releases download

**Describe the bug**
When registering a user on the site the data of custom fields in the user profile is not saved, except for the uploaded avatar.

**To Reproduce**
1. Go to Utilities : Edit Profile Fields
2. Click on edit location field and switch on 'Show on register form'
3. Go to site register page and fill out the form
4. Go to the new user profile page
5. You will see a blank profile with no details
6. Also missing metadata for 'location'

**Additional context**
No 3rd party installed plugins.
No profile types in 'Profile manager' settings.
No categories in 'Profile manager' settings.

**Comment by RiverVanRain** [comment]
Seems, you've missed `$custom_profile_fields` in https://github.com/ColdTrick/profile_manager/blob/master/classes/ColdTrick/ProfileManager/Users.php#L37 when you created [the release](https://github.com/ColdTrick/profile_manager/releases/tag/v15.0.2)

**Comment by jdalsem** [comment]
This has been fixed. You need to download release 15.0.3 (if you still are on Elgg v3.x)
