### ISSUE TITLE
Cannot activate the plugin on Elgg 5

### ISSUE THREAD

**Issue by nlybe** [ColdTrick/profile_manager#129]
**Elgg version**
Which version of Elgg are you using: v5.0.0-beta.1

**Plugin version**
Which version of the plugin are you using: 19.0

**Plugin source**
- Composer installation

**Describe the bug**
I installed the plugin using the composer. When trying to activate the plugin I get the following error:

profile_manager (guid: 55) cannot start and has been deactivated. Reason: No entry or class found for 'hooks'

I tried in 2 different Elgg 5 installations, both using the composer.

**To Reproduce**
1. Install the plugin using the composer
2. Activate the plugin from the admin console / plugins list
3. I get a white screen
4. When go back to the admin console, the error message is displayed

**Expected behavior**
Activate the plugin without issues

**Comment by jdalsem** [comment]
Did you install profile manager from Github master branch? It looks like you are using 'old' profile manager code. The word hooks does not exist in the current code for profile manager. If you install Profile Manager from composer you need to make sure to use the 'dev-master' branch. You can not rely on version numbers as Profile Manager has not had an  official release for Elgg 5.

**Comment by nlybe** [comment]
It worked, thank you.
