### ISSUE TITLE
"Profile Fields" based on "Profile Type"

### ISSUE THREAD

**Issue by rohit1290** [ColdTrick/profile_manager#130]
Can the profile fields be configured based on profile type? Example: If I created a profile type "Company", I would like to keep the website field enabled for this type of account but if I have another profile type "Student", then the website field would not be relevant. I see that we have the option to create profile types and categories, but I could not find anything where I can map those to fields.

Elgg: v6.0.1
Plugin: v22.0

Also, if possible, can we make the profile type such that an admin can only change it? similar to other fields.

**Comment by jdalsem** [comment]
You can link categories to types and fields to categories, so you can create a Profile Type 'Company' with the category 'Company Details' with the field 'Website'.

In the plugin settings you can configure who is allowed to change the profile type

**Comment by rohit1290** [comment]
Sorry for reaching out again. I have looked everywhere but did not found the option to link fields to categories. Can you help me with that.

**Comment by RiverVanRain** [comment]
> Sorry for reaching out again. I have looked everywhere but did not found the option to link fields to categories. Can you help me with that.

Reproducing:

- Create 'Students' and 'Teachers' profile types
- Create 'people' category
- Link types to this category
- Create a new 'Country' field
- Now drag this field to the top and place to 'people' category
- Click on 'people' category to view 'Country' field

Now all types linked to 'people' category will fill out 'Country' field

https://t.me/elggchat/1893

**Comment by jdalsem** [comment]
Yep, dragging and dropping will do the trick
