### ISSUE TITLE
Default profile type option listed on profile edit page

### ISSUE THREAD

**Issue by beck24** [ColdTrick/profile_manager#60]
When disabled on registration I think it implies that the defined profile types are the only ones wanted on the system.  When you allow the users to change profile types there is the 'default' option on the profile edit form even though it was disabled for registration.
I think it should be disabled if disabled on registration.
If not, maybe a secondary setting for that?

**Comment by jdalsem** [comment]
Fixed in https://github.com/ColdTrick/profile_manager/commit/2252f1ef9455fc5c4460678f5d926d0c5c07f401
