### ISSUE TITLE
problem on site search when plugin is enabled

### ISSUE THREAD

**Issue by nlybe** [ColdTrick/profile_manager#66]
Elgg 1.9, the global elgg site search is not working, returns the following error message

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AND msv.string LIKE '%SEARCHSTRING%'))) AND ((e.type = 'user')) AND (e.site_guid IN ' at line 1

**Comment by jdalsem** [comment]
I've tried to reproduce this issue, but are unable to do so on a 1.9.6 and 1.9.8 install with only the following plugins enabled (Profile, Profile Manager and Search). If you have more info on how to reproduce this issue please let me know

**Comment by nlybe** [comment]
Hi Jeroen
I have faced this issue in 3 different sites. When disable profile manager plugin, site search is working normally.

You can have a look at 
http://demo.agoramap.com/elgg19/ (site I own)
http://www.wargame.toys/ (customer site under development)

These sites are both Elgg 1.9 (1.9.8 and 1.8.7) with different plugins enabled.
You can make registration and I can make you admin if you wish.

Regards
Nikos

**Comment by jdalsem** [comment]
did you install the latest (correct) versions? Can you confirm you have the problem with all other (non related) plugins disabled?

**Comment by nlybe** [comment]
I just made a fresh installation of Elgg 1.9 and I only enabled profile_manager plugin, the latest version. I get the same error.
Have a look at http://dev.agoramap.com/elgg19/

**Comment by jdalsem** [comment]
i can confirm it, but the fix is also simple... you need to add at least 1 profile field (or import the default). The bug is related to core (the search plugin). I will file a ticket there..

**Comment by nlybe** [comment]
Thanks Jeroen. It's good that the fix was so simple
Keep doing good work
Nikos
