### ISSUE TITLE
Default profile type on registration form does not work

### ISSUE THREAD

**Issue by Pasley70** [ColdTrick/profile_manager#67]
Settings:

* Walled garden
* "Default profile type on registration form": [specific profile-type]
* "Hide the 'Default' profile type on registration form": yes 

User get the correct profile-fields on the registration-form, but after the registration the user has the profile-type "Default"

**Comment by jdalsem** [comment]
There is probably a conflict with another setting ("Who can change profile type"). If that setting is set to "admin", profile type selection on the register page is not able, thus the correct default is not set. Can you test with the setting set to "user"?

**Comment by Pasley70** [comment]
Yes, thats it. Maybe you need a hidden field
<pre>custom_profile_fields_custom_profile_type</pre>
on the registration form with the value of the predefined profile type? Or a hint for the action to set the profile-type in this case to the predefined profile type?
