### ISSUE TITLE
Profile Manager breaks javascript in page

### ISSUE THREAD

**Issue by insideth** [ColdTrick/profile_manager#68]
This problem is faced editing the profile with Elgg 1.9.8 and last PM plugin version, in Elgg 1.10.2 works ok. Please read the explanation here https://community.elgg.org/discussion/view/2033907/somethig-is-going-wrong-with-javascript

**Comment by jdalsem** [comment]
Thanks for reporting. Latest master version already has a fix for this: https://github.com/ColdTrick/profile_manager/commit/355eddc0f305c981faa650fdb162499513cdc32f
