### ISSUE TITLE
Profile Manager overrides default group's fields makind them dissapear

### ISSUE THREAD

**Issue by Yaco** [ColdTrick/profile_manager#71]
Hi!
I think this should be consider a bug: when you activate Profile Manager the default group's fields just dissapear. Is not possible to set the description, short description and tags of the group.

Hope this can be fixed soon.

Thanks for the great plugin!

**Comment by jdalsem** [comment]
THis is because Profile Manager is taking over management of these fields. If you go to the management of the profile fields, you can import the default group profile fields and you are back up and running.

**Comment by Yaco** [comment]
I tried with the button "Import default fields" and i get the following error: 
```Form is missing __token or __ts fields```

Any clue?

**Comment by jdalsem** [comment]
you either have a incorrect version of Elgg or of this plugin
