### ISSUE TITLE
When a new user registers on the site, the admin does not receive a notification

### ISSUE THREAD

**Issue by olairmarcos** [ColdTrick/profile_manager#74]
Hello,
I'm using the plugin manager profile to create a registration form on the site
When a new user registers on the site, the admin does not receive a notification in your email informing of the new record.
I have the plugin notification enabled on the site and also all notifications brands in the administrator's settings panel.
Its do or set up so that the administrator receives notification when a user registers on the site?
thank you

**Comment by jdalsem** [comment]
Normally Elgg does not notify a site admin of a new registration. At least profile manager is not sending them. There is no plugin available that i know of currently that sends out a notification to the admin when there is a new registration.
