### ISSUE TITLE
Add field upload image for the profile list.

### ISSUE THREAD

**Issue by olairmarcos** [ColdTrick/profile_manager#78]
Add a field where it is possible to upload an image (jpg, png) for the profile. This field must have the same settings as the other fields, ability to make compulsory, show the registration form and also show the group.
Example of use: Upload a picture of a certificate. Upload a picture membership card image.
Thanks

**Comment by jdalsem** [comment]
We had this feature in the past... It was never migrated to the newer versions of this plugin. Why do you need this as a profile file field? You could also use the file plugin to upload files...

**Comment by olairmarcos** [comment]
Example of use: With the addition of this feature allows the user to register on the site and upload a picture of your portfolio club member and thus have approved your account to access the community. If the user does not upload the image of your membership card when you register on the site, so it does not have the bill approved by the administrator. Thanks.

**Comment by jdalsem** [comment]
The file upload on register feature will not be added to Profile Manager plugin. Feel free to extend profile manager or the register form with your own plugin.
