### ISSUE TITLE
Issue when editing a profile with a multiselect field

### ISSUE THREAD

**Issue by bruno-infotrad** [ColdTrick/profile_manager#79]
I seem to be encountering an issue wih a multiselect field. 
The field is configured as shown below
https://drive.google.com/file/d/0BxCuFK1pAGz0blVZNXVuU2xPbEk/view?usp=sharing

When adding a user, the multiselect is displayed as expected. However, when I edit the profile, I see the image below
https://drive.google.com/file/d/0BxCuFK1pAGz0eWJTd2ozNHFVdG8/view?usp=sharing

Plugin version: 9.1
Elgg version: 1.12

**Comment by bruno-infotrad** [comment]
When I moved your group_tools plugin <b>after</b> the profile_manager plugin in the admin plug,in list, the issue disappeared. Not sure if it is normal or if you want to check by yourself before closing this issue....

**Comment by jdalsem** [comment]
I tried to reproduce this with the master build... i am not able to reproduce. Please let me know if you can reproduce this on a clean install
