### ISSUE TITLE
unable to save profile changes

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/profile_manager#82]
i have had a report that someone is unable to save the profile data and edit their profile after signing up and signing in. she entered her data and clicked save, but was informed that the form wouldn't be saved because the website field (a custom field) was not filled in.
the custom website field is a url field type and is set to not be mandatory.
i have looked in the error logs and don't see anything relevant and also have used 'login as' to sign in as her, but i can save the field data fine.
the two aspects that i cannot easily replicate are that she is using chrome on windows 10 (i don't have windows 10) and also she is in sweden and the locale is being set (presumably via the browser) to be sweden. i don't think the language file will be the cause of this.. but i thought i'd mention it anyway as i have no clue as to what the problem is here.
i have checked my theme and nothing is over-riding the profile edit page as far as i am aware.

any thoughts are welcome.

**Comment by jdalsem** [comment]
Currently i am unaware of issues like this. But thanks for reporting it. I am closing this as there is no way to reproduce this problem and it might as well be a user mistake
