### ISSUE TITLE
Version 9.2 not working in Elgg 1.12.8

### ISSUE THREAD

**Issue by Yaco** [ColdTrick/profile_manager#88]
Hi!
I am trying to use the plugin (version 9.2) with the LTS version of Elgg (1.12.8). But is not working, I got the following error when I go into the Profile Manager configuration page:

```Fatal error: Call to undefined method ElggObject::getTitle() in /srv/elgg/mod/profile_manager/views/default/plugins/profile_manager/settings.php on line 48```

Can you help me?

**Comment by jdalsem** [comment]
Did you install 9.2 via composer or did you download the source code from github...

**Comment by Yaco** [comment]
I downloaded the release zip file from github. Thx.

**Comment by jdalsem** [comment]
Was this the first time the plugin is used on this site? 

It seems the Class for profile types is not registered in the database.. there is a runonce function (profile_manager_run_once) that should register the correct classes with the entities...

**Comment by jdalsem** [comment]
If you have more information please let me know. I am closing it for now
