### ISSUE TITLE
Registration validation not working for multiselect

### ISSUE THREAD

**Issue by beck24** [ColdTrick/profile_manager#89]
This appears to be due to a hidden input with the same name preceding the multiselect.  The js finds a null value for the hidden input and counts it as an error even if there are values assigned in the multiselect.

**Comment by jdalsem** [comment]
Can you retest with the latest master? I have made some changes to the multiselect and currently can not reproduce your issue.

**Comment by jdalsem** [comment]
Please let me know if the latest master still has the issue...
