### ISSUE TITLE
Store terms_accepted setting and date per user

### ISSUE THREAD

**Issue by Wouter0100** [ColdTrick/profile_manager#91]
Mostly used for juridical questions, when you for example at first don't have the terms feature enabled, but later you've enabled it, and you'd like to know which users accepted your terms and when.

The when date could also be in handy for when you're chancing the terms.

**Comment by jdalsem** [comment]
@Wouter0100 i believe this is already stored as a private setting on register of a new user. See: https://github.com/ColdTrick/profile_manager/blob/master/classes/ColdTrick/ProfileManager/Users.php#L204
