### ISSUE TITLE
Fatal Error on User Registration on elgg 2.3

### ISSUE THREAD

**Issue by DaveONchE** [ColdTrick/profile_manager#95]
When profile Icon for registration is enabled, users registration return Fatal Error. I downloaded the most recent version of profile_manager for elgg 2.3 and I still experience same issue. Thanks,

**Comment by jdalsem** [comment]
There is already a fix for that in https://github.com/ColdTrick/profile_manager/commit/50f65cde35aa8ae30a12fdfd1ebabc4387e34f11. There has not yet been a release of profile manager with this commit however.
